name: Build APK
on: [push, workflow_dispatch]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
      - name: Unzip project
        run: unzip -q YtAudio.zip
      - name: Fix config
        run: echo "android.useAndroidX=true" > YtAudio/gradle.properties
      - name: Update library version
        run: sed -i 's/0.17.2/0.18.1/g' YtAudio/app/build.gradle.kts
      - name: Add yt-dlp auto update
        run: sed -i 's|ready = true|runCatching { YoutubeDL.getInstance().updateYoutubeDL(applicationContext, YoutubeDL.UpdateChannel.NIGHTLY) }; ready = true|' YtAudio/app/src/main/java/com/example/ytaudio/MainActivity.kt
      - name: Build
        run: cd YtAudio && gradle assembleDebug
      - name: Publish APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: YtAudio/app/build/outputs/apk/debug/app-debug.apk
